AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  SAM application for testing Lambdas related to WebSocket API
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DATASOURCE_CLASS:  org.postgresql.Driver
        DATASOURCE_URL: jdbc:postgresql://localhost:5432/demo
        DATASOURCE_USERNAME: demo
        DATASOURCE_PASSWORD: demo
        WEBSOCKET_CONNECTION_URL: https://4hpwfyvie6.execute-api.us-east-2.amazonaws.com/test/

Resources:
  WebsocketConnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-ws-connect
      CodeUri: websocket-connect/build/distributions/websocket-connect.zip
      Handler: com.chimauwah.aws.websocket.WebsocketConnectHandler::handleRequest
      MemorySize: 256
      Runtime: java8

  WebsocketDisconnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-ws-disconnect
      CodeUri: websocket-disconnect/build/distributions/websocket-disconnect.zip
      Handler: com.chimauwah.aws.websocket.WebsocketDisconnectHandler::handleRequest
      MemorySize: 256
      Runtime: java8

  WebsocketError:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-ws-error
      CodeUri: websocket-error/build/distributions/websocket-error.zip
      Handler: com.chimauwah.aws.websocket.WebsocketErrorHandler::handleRequest
      MemorySize: 256
      Runtime: java8

  WebsocketReceiveMessage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-ws-receivemessage
      CodeUri: websocket-receivemessage/build/distributions/websocket-receivemessage.zip
      Handler: com.chimauwah.aws.websocket.WebsocketReceiveMessageHandler::handleRequest
      MemorySize: 256
      Runtime: java8

  WebsocketBackendSendMessage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-ws-backend-sendmessage
      CodeUri: websocket-backend-sendmessage/build/distributions/websocket-backend-sendmessage.zip
      Handler: com.chimauwah.aws.websocket.WebSocketBackendSendMessageHandler::handleRequest
      MemorySize: 256
      Runtime: java8

